latency-wait: 120
reason: True
show-failed-logs: True
keep-going: True
printshellcmds: True
# Cluster submission
jobname: "{rule}.{jobid}"              # Provide a custom name for the jobscript that is submitted to the cluster.
jobs: 400                              #Use at most N CPU cluster/cloud jobs in parallel.

#cluster: "sbatch --output=\"jobs/{rule}/slurm_%x_%j.out\" --error=\"jobs/{rule}/slurm_%x_%j.log\" --mem={resources.mem_mb} --time={resources.runtime} --parsable"
# singularity
use-singularity: True
singularity-args: "--bind /wynton/home/doudna/bellieny-rabelo/nidali_db /scratch/bellieny-rabelo/nidali_output"
# Job resources
#set-resources:
#  - helloSingularity:mem_mb=1000
#  - helloSingularity:runtime=00:03:00
# For some reasons time needs quotes to be read by snakemake
#default-resources:
#  - mem_mb=500
#  - runtime="00:01:00"
# Define the number of threads used by rules
#set-threads:
#  - helloSingularity=1