# === Directory- and File Paths
# Path to parent directory where query and database are stored
run: "/groups/doudna/projects/daniel_projects/yoon_ph"

# Filename prefix for individual lists of entry IDs
dat_id_list_prefix: "list_batch_"

# Path to dali.pl script
dali_path: ""

# === Run-associated variables

# Range of batches within the database to be processed
batch_range: [1,10]


