# === Directory- and File Paths
# Path to parent directory where query and database are stored
run: "/scratch/bellieny-rabelo/nidali_output"
# "/scratch/bellieny-rabelo/nidali_output"
# "/groups/doudna/projects/daniel_projects/yoon_ph/nidali_smk_output"
db_dir: "/wynton/home/doudna/bellieny-rabelo/nidali_db"
#  "/groups/doudna/projects/daniel_projects/yoon_ph"
# "/wynton/home/doudna/bellieny-rabelo/nidali_db"

threads: 1

# Filename prefix for individual lists of entry IDs
dat_id_list_prefix: "list_batch_"

# === Run-associated variables
# Range of batches within the database to be processed
batch_range: [1,10]

query_name: ["13AFA", "13CNA"]

