# === Directory- and File Paths
# Path to parent directory where query and database are stored
run: "/wynton/home/doudna/bellieny-rabelo/nidali_output/yoon_multidomain"

# This var expects a subdir called: pdb_files_DAT/batch_\d+
db_dir: "/wynton/home/doudna/bellieny-rabelo/nidali_db"

# This is where *.dat files are stored
input_dir: "/wynton/home/doudna/bellieny-rabelo/nidali_queries/yoon_multidomain"

# Don't touch!
tmpdir: '$TMPDIR'

# Dali's bin/ folder
dali_path: "/wynton/home/doudna/bellieny-rabelo/projects/dali_install/DaliLite.v5/bin"

# According to the 'cluster' variable in: profile/config.yaml
threads: 15

# DON't TOUCH: Filename prefix for individual lists of entry IDs
dat_id_list_prefix: "list_batch_"

# Alphafold ID conversion table
id_convert: "/wynton/home/doudna/bellieny-rabelo/projects/nidali/dump/clustered_AFDB_structure_key.txt"

# === Run-associated variables
# Range of batches within the database to be processed
batch_range: [0,2302]

query_name: ["1a4eA", "1cc1L", "1cc1S", "1d3yA", "1dd9A", "1et0A", "1fvhA", "1gnlA", "1h5wA", "1i2aA", "1io1A", "1jmuA", "1k8tA", "1k9oI", "1ka1A", "1knzA", "1kyqA", "1ldjA", "1lfpA", "1m1cA", "1mw9X", "1nh1A", "1no7A", "1oisA", "1q88A", "1r6fA", "1sg6A", "1sr8A", "1srqA", "1szqA", "1twfB", "1u7lA", "1u8vA", "1urjA", "1vddA", "1vkyA", "1x87A", "1xqbA", "1z0sA", "1zbpA", "1zjcA", "2avuE", "2azeA", "2b3tB", "2btvA", "2dcfA", "2ffjA", "2fiyA", "2gafD", "2hhvA", "2hq2A", "2i06A", "2i0zA", "2i5hA", "2i71A", "2ijrA", "2o3iA", "2oezA", "2p62A", "2yzsA", "3aa0A", "3cw9A", "3jclA", "3nuhB", "3nwaA", "3rlfF", "3vb9A", "4an8A", "4ckkA", "4dynA", "4ogcA", "4wsbC", "5d9aA", "5id6A"]
